export const types = Object.freeze({
  USER_SET_SEED: "USER_SET_SEED",
  USER_START_FETCHING: "USER_START_FETCHING",
  USER_STOP_FETCHING: "USER_STOP_FETCHING",
  USER_SET_FETCHING_ERROR: "USER_SET_FETCHING_ERROR",
  USER_FILL: "USER_FILL",
});
