export const types = Object.freeze({
  CONTACTS_START_FETCHING: "CONTACTS_START_FETCHING",
  CONTACTS_STOP_FETCHING: "CONTACTS_STOP_FETCHING",
  CONTACTS_SET_FETCHING_ERROR: "CONTACTS_SET_FETCHING_ERROR",
  CONTACTS_FILL: "CONTACTS_FILL",
  CONTACTS_VIEW: "CONTACTS_VIEW",
  CONTACTS_SET_FILTER_DATA: "CONTACTS_SET_FILTER_DATA",
  CONTACTS_SET_PAGE_STATE: "CONTACTS_SET_PAGE_STATE",
});
